# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 6e35ae2e-9d69-41de-b205-17ebf1bc9436-capi-aws-check
  namespace: 6e35ae2e-9d69-41de-b205-17ebf1bc9436
spec:
  template:
    metadata:
      name: 6e35ae2e-9d69-41de-b205-17ebf1bc9436-capi-aws
    spec:
      serviceAccountName: 6e35ae2e-9d69-41de-b205-17ebf1bc9436-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 6e35ae2e-9d69-41de-b205-17ebf1bc9436
        - 6e35ae2e-9d69-41de-b205-17ebf1bc9436
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 6e35ae2e-9d69-41de-b205-17ebf1bc9436-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
